### ISSUE TITLE
Ubuntu Exception: The location of Firebird Client Library could not be determined.

### ISSUE THREAD

**Issue by mahmoud-ferig** [FirebirdSQL/python3-lib#1]
I installed this package on my ubuntu but it doesn't work and return this error message:
```
Traceback (most recent call last):
  File "try.py", line 38, in <module>
    create_database("employee")
  File "/home/nulladji/.local/lib/python3.8/site-packages/firebird/driver/core.py", line 2178, in create_database
    dpb.get_buffer(for_create=True), db_config.sql_dialect.value,
  File "/home/nulladji/.local/lib/python3.8/site-packages/firebird/driver/core.py", line 589, in get_buffer
    with a.get_api().util.get_xpb_builder(XpbKind.DPB) as dpb:
  File "/home/nulladji/.local/lib/python3.8/site-packages/firebird/driver/fbapi.py", line 2051, in get_api
    load_api()
  File "/home/nulladji/.local/lib/python3.8/site-packages/firebird/driver/fbapi.py", line 2042, in load_api
    _api = FirebirdAPI(filename)
  File "/home/nulladji/.local/lib/python3.8/site-packages/firebird/driver/fbapi.py", line 1924, in __init__
    raise Exception("The location of Firebird Client Library could not be determined.")
Exception: The location of Firebird Client Library could not be determined.
```

please anyone has any advice for me to solve this error?
thank you

**Comment by pcisar** [comment]
This is a support question. You need Firebird client installed (libfbclient.so). If you have it installed, check whether it could be found by ctypes (https://docs.python.org/3/library/ctypes.html#finding-shared-libraries). You may also specify it directly via configuration (see https://firebird-driver.readthedocs.io/en/latest/usage-guide.html#the-driver-config-object)
